doc: Replace doc_auto_cfg by doc_cfg
doc_auto_cfg has been merged into doc_cfg:

error[E0557]: feature has been removed
 --> src/lib.rs:2:40
  |
2 | #![cfg_attr(all(doc, nightly), feature(doc_auto_cfg))] // expect nightly for doc
  |                                        ^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in CURRENT_RUSTC_VERSION; see <https://github.com/rust-lang/rust/pull/138907> for more information
  = note: merged into `doc_cfg`

Signed-off-by: Hanna Czenczek <hreitz@redhat.com>